import sys
import os
import json
import types
import traceback
from importlib.machinery import ModuleSpec
import importlib.metadata

# =====================================================================
# 💾 State Management & Path Resolution
# =====================================================================
# 自动检测激活的虚拟环境路径
venv_path = os.environ.get("VIRTUAL_ENV")

# 兜底机制：如果没有 VIRTUAL_ENV 环境变量，但 sys.prefix 显示在虚拟环境中
if not venv_path and sys.prefix != getattr(sys, "base_prefix", sys.prefix):
    venv_path = sys.prefix

if venv_path:
    # 固定保存在 .venv 目录下
    STATE_FILE = os.path.join(venv_path, ".mock_state.json")
else:
    # 如果没有使用虚拟环境，则退回到当前目录的绝对路径
    STATE_FILE = os.path.abspath(".mock_state.json")

print(f"[⚙️ Ghost Engine] State file locked to: {STATE_FILE}") # 加上这句方便你在日志里确认路径

mock_state = {"env": {}, "mocked_imports": {}, "core_imports": {}}

# =====================================================================
# 💾 State Management
# =====================================================================
if os.path.exists(STATE_FILE):
    try:
        with open(STATE_FILE, "r") as f:
            mock_state.update(json.load(f))
    except Exception:
        pass

def _update_state_and_save(patch):
    """Receive patch from LLM and distribute it to the corresponding Package's territory"""
    print(f"✨ [Fix Successful] Patch generated by LLM: {patch}")
    
    if "env" in patch:
        mock_state.setdefault("env", {}).update(patch["env"])

    if "api_features" in patch:
        for sig_key, feature_dict in patch["api_features"].items():
            root_pkg = sig_key.split('.')[0].split('(')[0]
            pkg_entry = mock_state.setdefault("mocked_imports", {}).setdefault(root_pkg, {})
            api_dict = pkg_entry.setdefault("api_features", {})
            api_dict[sig_key] = feature_dict

    if "mocked_imports" in patch:
        for pkg_name, pkg_data in patch["mocked_imports"].items():
            pkg_entry = mock_state.setdefault("mocked_imports", {}).setdefault(pkg_name, {})
            if "api_features" in pkg_data:
                pkg_entry.setdefault("api_features", {}).update(pkg_data["api_features"])
                
    with open(STATE_FILE, "w") as f:
        json.dump(mock_state, f, indent=4)
    print(f"✅ Patch smartly routed and written to {STATE_FILE}.")

# =====================================================================
# 🎯 Fetch Requirements and Whitelist configuration paths from env
# =====================================================================
ALLOWED_MOCKS = set()
req_file = os.environ.get("MOCK_REQ_FILE")

# Map common PyPI package names to their corresponding import names
KNOWN_ALIASES = {
    "pyyaml": "yaml",
    "beautifulsoup4": "bs4",
    "pillow": "pil",
    "python_dateutil": "dateutil",
    "djangorestframework": "rest_framework",
    "pyjwt": "jwt",
    "python_dotenv": "dotenv",
    "opencv_python": "cv2",
    "scikit_learn": "sklearn",
}

if req_file and os.path.exists(req_file):
    import re
    with open(req_file, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"): continue
            match = re.match(r'^([A-Za-z0-9_\.-]+)', line)
            if match:
                pkg = match.group(1).lower().replace('-', '_')
                ALLOWED_MOCKS.add(pkg)
                if pkg in KNOWN_ALIASES:
                    ALLOWED_MOCKS.add(KNOWN_ALIASES[pkg])

# =====================================================================
# 📦 Real Dependency Scanner
# =====================================================================
def _record_core_imports():
    try:
        installed_packages = {
            dist.metadata["Name"]: dist.version 
            for dist in importlib.metadata.distributions()
        }
        if mock_state.get("core_imports") != installed_packages:
            mock_state["core_imports"] = installed_packages
            with open(STATE_FILE, "w") as f:
                json.dump(mock_state, f, indent=4)
    except Exception:
        pass

_record_core_imports()

# Inject mocked environment variables
for key, value in mock_state.get("env", {}).items():
    if key not in os.environ:
        os.environ[key] = str(value)

def _record_mocked_import(fullname):
    base_name = fullname.split('.')[0] 
    if base_name not in mock_state["mocked_imports"]:
        mock_state["mocked_imports"][base_name] = {"api_features": {}}
        try:
            with open(STATE_FILE, "w") as f:
                json.dump(mock_state, f, indent=4)
        except Exception:
            pass

# =====================================================================
# 🛡️ Underlying Framework Whitelist
# =====================================================================
IGNORED_MODULES = set()

whitelist_file = os.environ.get("MOCK_WHITELIST_FILE")
if not whitelist_file and os.path.exists("whitelist.txt"):
    whitelist_file = "whitelist.txt"

if whitelist_file and os.path.exists(whitelist_file):
    with open(whitelist_file, "r", encoding="utf-8") as f:
        for line in f:
            line = line.split('#')[0].strip()
            if line:
                IGNORED_MODULES.add(line.lower().replace("-", "_"))

# =====================================================================
# 📸 1. Logical Signature Recorder
# =====================================================================
_recent_mock_calls = []

def _get_logical_signature(name, args=None, kwargs=None):
    """Generate logical signature: e.g., 'jwt.decode(...)'"""
    if args is None and kwargs is None:
        return name 
    
    arg_reprs = [repr(a)[:50] for a in (args or [])]
    kwarg_reprs = [f"{k}={repr(v)[:50]}" for k, v in (kwargs or {}).items()]
    signature = f"{name}({', '.join(arg_reprs + kwarg_reprs)})"
    return signature

def _track_and_get_mock(sig_key):
    _recent_mock_calls.append(sig_key)
    if len(_recent_mock_calls) > 100: 
        _recent_mock_calls.pop(0)

    root_pkg = sig_key.split('.')[0].split('(')[0]
    res = mock_state.get("mocked_imports", {}).get(root_pkg, {}).get("api_features", {})
    
    def _extract_return(feature_data):
        if isinstance(feature_data, dict) and "return_value" in feature_data:
            return feature_data["return_value"]
        return feature_data

    # 1. Full logical signature match
    if sig_key in res: 
        return _extract_return(res[sig_key])
        
    # 2. Downgrade match: Base API path
    base_name = sig_key.split('(')[0]
    if base_name in res: 
        return _extract_return(res[base_name])
    if f"{base_name}()" in res: 
        return _extract_return(res[f"{base_name}()"])
        
    # 3. Ultimate downgrade: Method name only
    api_name = base_name.split('.')[-1]
    if api_name in res:
        return _extract_return(res[api_name])
    if f"{api_name}()" in res:
        return _extract_return(res[f"{api_name}()"])
            
    return None

# =====================================================================
# 👻 2. Static Ghost Engine (OPTION A: ORIGIN INTERCEPTION)
# =====================================================================
class LLMMockProxyMeta(type):
    def __instancecheck__(cls, instance): return True
    def __subclasscheck__(cls, subclass): return True

class LLMMockProxy(metaclass=LLMMockProxyMeta):
    def __init__(self, name, *args, **kwargs):
        object.__setattr__(self, '_name', name)
        object.__setattr__(self, '__bases__', (object,))
        object.__setattr__(self, '__mro__', (self, object))

    def __mro_entries__(self, bases):
        def mock_init_subclass(cls, **kwargs): pass
        mock_base = type(self._name, (object,), {
            '__module__': '__main__',
            '__qualname__': self._name,
            '__init_subclass__': classmethod(mock_init_subclass),
        })
        return (mock_base,)

    def __getattr__(self, item):
        if item in ('_name', '__bases__', '__mro__'):
            return object.__getattribute__(self, item)
        if item in ('__path__', '__file__', '__spec__'):
            raise AttributeError(item)
        if item == '__name__':
            return self._name
        if item == '__class__':
            return type(self._name, (object,), {})

        full_path = f"{self._name}.{item}"
        sig_key = _get_logical_signature(full_path)

        # Look for explicit attribute mock (e.g., constants)
        mock_val = _track_and_get_mock(sig_key)
        if mock_val is not None:
            return mock_val

        if "Error" in item or "Exception" in item:
            class MockException(Exception): pass
            MockException.__name__ = item
            return MockException

        if item.startswith('__') and item.endswith('__'):
            raise AttributeError(item)

        # Return proxy to allow chaining (e.g., module.submodule.func())
        # The halt will happen in __call__ if the user actually invokes it.
        return LLMMockProxy(full_path)

    def __setattr__(self, name, value):
        if name in ('_name', '__bases__', '__mro__'):
            object.__setattr__(self, name, value)
        pass

    def __call__(self, *args, **kwargs):
        sig_key = _get_logical_signature(self._name, args, kwargs)
        mock_val = _track_and_get_mock(sig_key)
        
        # 1. Perfect Hit: Return LLM's patched data
        if mock_val is not None:
            return mock_val

        def _safe_repr(val, max_len=150):
            try:
                r = repr(val)
                if len(r) > max_len:
                    return r[:max_len//2] + "..." + r[-max_len//2:]
                return r
            except Exception:
                return "<Unrepresentable Object>"

        call_details = {
            "api_path": str(self._name),
            "signature": str(sig_key),
            "args": [_safe_repr(a) for a in args],
            "kwargs": {str(k): _safe_repr(v) for k, v in kwargs.items()}
        }
            
        # 2. FAIL FAST: API lacks mock data. Halt execution immediately!
        print(f"\n" + "🔥"*25)
        print(f"🚨 [Origin Intercept] API '{self._name}' called but lacks mock data.")
        print(f"📦 Arguments intercepted: args={call_details['args']}, kwargs={call_details['kwargs']}")
        print(f"🛑 Halting execution and consulting LLM Agent...")
        print("🔥"*25 + "\n")
        
        # Capture the current stack trace omitting this immediate function call
        tb_list = traceback.format_stack()[:-1]
        tb_str = "".join(tb_list)
        
        error_msg = (
            f"MockMissingError: Execution halted at '{sig_key}'. The mock engine requires a return value for this API call to proceed.\n\n"
            f"Full Arguments intercepted:\n{json.dumps(call_details, indent=2)}\n\n"
            f"⚠️ TASK: You MUST generate a JSON patch to mock this API.\n"
            f"For the API ('{sig_key}'), provide ONLY:\n"
            f"1. 'description' (what the API does)\n"
            f"2. 'return_value' (the mocked output required to bypass this failure and satisfy the business logic).\n\n"
            f"Expected JSON Format:\n"
            f"{{\n"
            f"  \"description\": \"...\",\n"
            f"  \"return_value\": ...\n"
            f"}}\n\n"
            f"Stack Trace:\n{tb_str}"
        )
        
        try:
            import llm_client
            patch = llm_client.API_feature(error_msg, _recent_mock_calls)
            if patch and "return_value" in patch:
                wrapped_patch = {
                    "api_features": {
                        sig_key: {
                            "description": patch.get("description", "Auto-generated mock by LLM"),
                            "parameters": {
                                "args": call_details["args"],
                                "kwargs": call_details["kwargs"]
                            },
                            "return_value": patch["return_value"]
                        }
                    }
                }
                _update_state_and_save(wrapped_patch)
                print("🛑 [LLM Mock] Patch applied with auto-injected parameters! Forcefully terminating process. Please restart.")
            else:
                print("❌ [Fix Failed] Agent failed to generate a valid remediation patch (missing 'return_value').")
        except Exception as ex: 
            print(f"⚠️ [System Error]: {ex}")
        
        # Suicide to allow external script/harness to restart with new state
        import os
        os._exit(1)

    def __iter__(self):
        yield LLMMockProxy(f"{self._name}_item")

    def __getitem__(self, key):
        sig_key = f"{self._name}[{repr(key)}]"
        mock_val = _track_and_get_mock(sig_key)
        if mock_val is not None:
            return mock_val
        # If subscript access lacks data, we can also halt here if needed
        return LLMMockProxy(sig_key)

    def __len__(self): return 1
    def __bool__(self): return True
    def __str__(self): return ""
    def __repr__(self): return self._name

class GhostModule(types.ModuleType):
    def __getattr__(self, name):
        full_path = f"{self.__name__}.{name}"
        sig_key = _get_logical_signature(full_path)
        
        mock_val = _track_and_get_mock(sig_key)
        if mock_val is not None:
            return mock_val
            
        if "Error" in name or "Exception" in name:
            class MockException(Exception): pass
            MockException.__name__ = name
            return MockException
            
        if name.startswith('__') and name.endswith('__'):
            raise AttributeError(name)
            
        return LLMMockProxy(full_path)

class GhostLoader:
    def __init__(self, fullname): self.fullname = fullname
    def create_module(self, spec):
        mod = GhostModule(self.fullname)
        mod.__path__ = []
        return mod
    def exec_module(self, module):
        module.__dict__.update({'__path__': []})

class GhostFinder:
    def find_spec(self, fullname, path, target=None):
        # 1. Filter out built-in and private modules
        if fullname.startswith('_') or fullname in sys.builtin_module_names:
            return None

        base_name = fullname.split('.')[0]

        if hasattr(sys, 'stdlib_module_names') and base_name in sys.stdlib_module_names:
            return None

        # 2. Filter out blacklisted modules (e.g., underlying framework modules)
        if base_name in IGNORED_MODULES:
            return None

        # ==================== Minimalist Core Logic ====================
        # Reaching this point means the standard PathFinder has already failed.
        # Therefore, the package is definitely NOT installed in the environment.

        # 3. Check if the package is in the requirements whitelist (ALLOWED_MOCKS)
        if ALLOWED_MOCKS and base_name not in ALLOWED_MOCKS:
            # Not in the whitelist: do not intercept. 
            # Return None to let the system naturally raise a ModuleNotFoundError.
            return None

        # 4. In the whitelist: initialize the Mock mechanism
        print(f"[⚙️ Ghost Engine] Auto-pretending successful import of uninstalled package: '{fullname}'")
        _record_mocked_import(fullname)
        return ModuleSpec(fullname, GhostLoader(fullname))

sys.meta_path.append(GhostFinder())