import sys
import os
import json
import types
import traceback
from importlib.machinery import ModuleSpec
import importlib.metadata

# =====================================================================
# 💾 State Management & Path Resolution
# =====================================================================
print(f"[⚙️ Ghost Engine] Execution mode: MOCK")

# 自动检测激活的虚拟环境路径
venv_path = os.environ.get("VIRTUAL_ENV")

# 兜底机制：如果没有 VIRTUAL_ENV 环境变量，但 sys.prefix 显示在虚拟环境中
if not venv_path and sys.prefix != getattr(sys, "base_prefix", sys.prefix):
    venv_path = sys.prefix

if venv_path:
    # 固定保存在 .venv 目录下
    STATE_FILE = os.path.join(venv_path, ".mock_state.json")
else:
    # 如果没有使用虚拟环境，则退回到当前目录的绝对路径
    STATE_FILE = os.path.abspath(".mock_state.json")

print(f"[⚙️ Ghost Engine] State file locked to: {STATE_FILE}")

mock_state = {"env": {}, "mocked_imports": {}, "core_imports": {}}

# =====================================================================
# 💾 State Management
# =====================================================================
if os.path.exists(STATE_FILE):
    try:
        with open(STATE_FILE, "r") as f:
            mock_state.update(json.load(f))
    except Exception:
        pass

def _update_state_and_save(patch):
    """Receive patch from LLM and distribute it to the corresponding Package's territory"""
    print(f"✨ [Fix Successful] Patch generated by LLM: {patch}")

    if "env" in patch:
        mock_state.setdefault("env", {}).update(patch["env"])

    if "api_features" in patch:
        for sig_key, feature_dict in patch["api_features"].items():
            root_pkg = sig_key.split('.')[0].split('(')[0]
            pkg_entry = mock_state.setdefault("mocked_imports", {}).setdefault(root_pkg, {})
            api_dict = pkg_entry.setdefault("api_features", {})

            # Handle the new parameter list format
            if sig_key in api_dict and isinstance(api_dict[sig_key], dict):
                existing_api = api_dict[sig_key]

                # If the existing API has a parameters field
                if "parameters" in existing_api:
                    # Convert old single-parameter format to list format if needed
                    if not isinstance(existing_api["parameters"], list):
                        existing_api["parameters"] = [existing_api["parameters"]]

                    # Add new parameter configuration to the list
                    if "parameters" in feature_dict:
                        new_param_config = feature_dict["parameters"]
                        # Create a new parameter entry with its return value
                        param_entry = {
                            "args": new_param_config.get("args", []),
                            "kwargs": new_param_config.get("kwargs", {}),
                            "return_value": feature_dict.get("return_value")
                        }
                        existing_api["parameters"].append(param_entry)

                        # Update description if provided
                        if "description" in feature_dict:
                            existing_api["description"] = feature_dict["description"]
                    else:
                        # No parameters in new patch, just update the API data
                        api_dict[sig_key] = feature_dict
                else:
                    # No existing parameters field, create new list format
                    if "parameters" in feature_dict:
                        new_param_config = feature_dict["parameters"]
                        param_entry = {
                            "args": new_param_config.get("args", []),
                            "kwargs": new_param_config.get("kwargs", {}),
                            "return_value": feature_dict.get("return_value")
                        }
                        api_dict[sig_key] = {
                            "description": feature_dict.get("description", "Auto-generated mock by LLM"),
                            "parameters": [param_entry]
                        }
                    else:
                        api_dict[sig_key] = feature_dict
            else:
                # New API entry - create with list format if parameters exist
                if "parameters" in feature_dict:
                    new_param_config = feature_dict["parameters"]
                    param_entry = {
                        "args": new_param_config.get("args", []),
                        "kwargs": new_param_config.get("kwargs", {}),
                        "return_value": feature_dict.get("return_value")
                    }
                    api_dict[sig_key] = {
                        "description": feature_dict.get("description", "Auto-generated mock by LLM"),
                        "parameters": [param_entry]
                    }
                else:
                    api_dict[sig_key] = feature_dict

    if "mocked_imports" in patch:
        for pkg_name, pkg_data in patch["mocked_imports"].items():
            pkg_entry = mock_state.setdefault("mocked_imports", {}).setdefault(pkg_name, {})
            if "api_features" in pkg_data:
                pkg_entry.setdefault("api_features", {}).update(pkg_data["api_features"])

    with open(STATE_FILE, "w") as f:
        json.dump(mock_state, f, indent=4, default=str)
    print(f"✅ Patch smartly routed and written to {STATE_FILE}.")

# =====================================================================
# 🎯 Fetch Requirements and Whitelist configuration paths from env
# =====================================================================
ALLOWED_MOCKS = set()
REQUIRED_PACKAGES = set()  # 💡 新增：用于记录 requirements 里声明的原始包名
req_file = os.environ.get("MOCK_REQ_FILE")

# =====================================================================
# 🗺️ PyPI Package Name to Import Name Mapping
# =====================================================================
# Load comprehensive mapping from external JSON file
KNOWN_ALIASES = {}

# Try to get mapping file path from environment variable first
MAPPING_FILE = os.environ.get("MOCK_MAPPING_FILE")

if MAPPING_FILE and os.path.exists(MAPPING_FILE):
    try:
        with open(MAPPING_FILE, "r", encoding="utf-8") as f:
            KNOWN_ALIASES = json.load(f)
        # print(f"[⚙️ Ghost Engine] Loaded {len(KNOWN_ALIASES)} package mappings from {MAPPING_FILE}")
    except Exception as e:
        raise RuntimeError(f"Failed to load mapping file: {e}")
else:
    raise FileNotFoundError(f"Mapping file not found at expected location: {MAPPING_FILE}")

def _resolve_import_name(pkg_name):
    """
    Resolve PyPI package name to actual import name.
    Try multiple normalization strategies to find the correct alias.

    Args:
        pkg_name: The package name to resolve (could be PyPI name or import name)

    Returns:
        The resolved import name, or the original name if no mapping found
    """
    # Normalize the package name for lookup
    normalized = pkg_name.lower().replace('-', '_')

    # Try direct lookup with normalized name
    if normalized in KNOWN_ALIASES:
        resolved = KNOWN_ALIASES[normalized]
        # print(f"[🗺️ Alias Resolver] '{pkg_name}' → '{resolved}'")
        return resolved

    # Try with hyphen version
    hyphenated = pkg_name.lower().replace('_', '-')
    if hyphenated in KNOWN_ALIASES:
        resolved = KNOWN_ALIASES[hyphenated]
        # print(f"[🗺️ Alias Resolver] '{pkg_name}' → '{resolved}'")
        return resolved

    # Try original case-insensitive lookup
    for key, value in KNOWN_ALIASES.items():
        if key.lower() == pkg_name.lower():
            # print(f"[🗺️ Alias Resolver] '{pkg_name}' → '{value}'")
            return value

    # No mapping found, return original name
    return pkg_name

if req_file and os.path.exists(req_file):
    import re
    with open(req_file, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"): continue
            # Extract the package name (ignoring version specifiers like ==, >=, etc.)
            match = re.match(r'^([A-Za-z0-9_\.-]+)', line)
            if match:
                raw_pkg = match.group(1)
                REQUIRED_PACKAGES.add(raw_pkg)  # Keep the exact PyPI name for version lookup

                # Normalize for internal mock routing (e.g., PyYAML -> pyyaml)
                pkg_normalized = raw_pkg.lower().replace('-', '_')
                ALLOWED_MOCKS.add(pkg_normalized)

                # Use the comprehensive resolver to find import name
                import_name = _resolve_import_name(raw_pkg)
                if import_name != raw_pkg and import_name != pkg_normalized:
                    ALLOWED_MOCKS.add(import_name)

# =====================================================================
# 📦 Real Dependency Scanner (Targeted Lookup)
# =====================================================================
def _record_core_imports():
    try:
        core_packages = {}
        # Iterate only through the packages explicitly listed in requirements
        for pkg in REQUIRED_PACKAGES:
            try:
                # Attempt to fetch the version of the installed package
                version = importlib.metadata.version(pkg)
                core_packages[pkg] = version
            except importlib.metadata.PackageNotFoundError:
                # Package is in requirements but NOT installed in the environment -> skip it
                continue
                
        # Update the state file only if there's a difference
        if mock_state.get("core_imports") != core_packages:
            mock_state["core_imports"] = core_packages
            with open(STATE_FILE, "w") as f:
                json.dump(mock_state, f, indent=4, default=str)
    except Exception:
        pass

_record_core_imports()

# Inject mocked environment variables
for key, value in mock_state.get("env", {}).items():
    if key not in os.environ:
        os.environ[key] = str(value)

def _record_mocked_import(fullname):
    base_name = fullname.split('.')[0] 
    if base_name not in mock_state["mocked_imports"]:
        mock_state["mocked_imports"][base_name] = {"api_features": {}}
        try:
            with open(STATE_FILE, "w") as f:
                json.dump(mock_state, f, indent=4, default=str)
        except Exception:
            pass

# =====================================================================
# 🛡️ Underlying Framework Whitelist
# =====================================================================
IGNORED_MODULES = set()

whitelist_file = os.environ.get("MOCK_WHITELIST_FILE")
if not whitelist_file and os.path.exists("whitelist.txt"):
    whitelist_file = "whitelist.txt"

if whitelist_file and os.path.exists(whitelist_file):
    with open(whitelist_file, "r", encoding="utf-8") as f:
        for line in f:
            line = line.split('#')[0].strip()
            if line:
                IGNORED_MODULES.add(line.lower().replace("-", "_"))

# =====================================================================
# 📸 1. Logical Signature Recorder
# =====================================================================
_recent_mock_calls = []

def _get_logical_signature(name, args=None, kwargs=None):
    """Generate logical signature: e.g., 'jwt.decode(...)'"""
    if args is None and kwargs is None:
        return name 
    
    arg_reprs = [repr(a)[:50] for a in (args or [])]
    kwarg_reprs = [f"{k}={repr(v)[:50]}" for k, v in (kwargs or {}).items()]
    signature = f"{name}({', '.join(arg_reprs + kwarg_reprs)})"
    return signature

def _track_and_get_mock(sig_key, args=None, kwargs=None):
    _recent_mock_calls.append(sig_key)
    if len(_recent_mock_calls) > 100:
        _recent_mock_calls.pop(0)

    root_pkg = sig_key.split('.')[0].split('(')[0]
    res = mock_state.get("mocked_imports", {}).get(root_pkg, {}).get("api_features", {})

    def _extract_return(feature_data):
        if isinstance(feature_data, dict) and "return_value" in feature_data:
            return feature_data["return_value"]
        # If return_value is missing, return None (allow APIs with no return value)
        return None

    def _match_parameters(stored_params, call_args, call_kwargs):
        """Match parameters based on stored parameter values"""
        if not isinstance(stored_params, dict):
            return True  # No parameters to match, accept any call

        stored_args = stored_params.get("args", [])
        stored_kwargs = stored_params.get("kwargs", {})

        # Check if both stored and call have no parameters (empty parameters case)
        if not stored_args and not stored_kwargs:
            # Empty parameters should only match empty calls
            return not call_args and not call_kwargs

        # Match args
        if stored_args:
            if not call_args or len(call_args) != len(stored_args):
                return False
            for i, (stored_arg, call_arg) in enumerate(zip(stored_args, call_args)):
                # Convert both to string for comparison
                if str(stored_arg) != str(repr(call_arg)[:150]):
                    return False

        # Match kwargs
        if stored_kwargs:
            if not call_kwargs:
                return False
            for key, stored_value in stored_kwargs.items():
                if key not in call_kwargs:
                    return False
                if str(stored_value) != str(repr(call_kwargs[key])[:150]):
                    return False

        return True

    def _search_in_parameters_list(parameters_list, call_args, call_kwargs):
        """Search through the list of parameter configurations to find a match"""
        if not isinstance(parameters_list, list):
            return None

        for param_config in parameters_list:
            if _match_parameters(param_config, call_args, call_kwargs):
                return param_config

        return None

    # Extract API name (without parentheses and parameters)
    base_name = sig_key.split('(')[0]

    # Try to match by API name and parameters
    if base_name in res:
        api_data = res[base_name]
        if isinstance(api_data, dict):
            if "parameters" in api_data:
                # Search through the list for a matching parameter configuration
                matched_config = _search_in_parameters_list(api_data["parameters"], args or [], kwargs or {})
                if matched_config:
                    # Return tuple: (found, return_value)
                    return (True, matched_config.get("return_value"))
                else:
                    # API found but no matching parameters - return (False, None) to trigger LLM
                    return (False, None)
            else:
                # No parameters stored, return the mock (backward compatibility)
                return (True, _extract_return(api_data))

    # Fallback: try method name only
    api_name = base_name.split('.')[-1]
    if api_name in res:
        api_data = res[api_name]
        if isinstance(api_data, dict):
            if "parameters" in api_data:
                matched_config = _search_in_parameters_list(api_data["parameters"], args or [], kwargs or {})
                if matched_config:
                    return (True, matched_config.get("return_value"))
                else:
                    return (False, None)
            else:
                return (True, _extract_return(api_data))

    # API not found in mock_state
    return (False, None)

# =====================================================================
# 👻 2. Static Ghost Engine (OPTION A: ORIGIN INTERCEPTION)
# =====================================================================
class LLMMockProxyMeta(type):
    def __instancecheck__(cls, instance): return True
    def __subclasscheck__(cls, subclass): return True

class LLMMockProxy(metaclass=LLMMockProxyMeta):
    def __init__(self, name, *args, **kwargs):
        object.__setattr__(self, '_name', name)
        object.__setattr__(self, '__bases__', (object,))
        object.__setattr__(self, '__mro__', (self, object))

    def __mro_entries__(self, bases):
        def mock_init_subclass(cls, **kwargs): pass
        mock_base = type(self._name, (object,), {
            '__module__': '__main__',
            '__qualname__': self._name,
            '__init_subclass__': classmethod(mock_init_subclass),
        })
        return (mock_base,)

    def __getattr__(self, item):
        if item in ('_name', '__bases__', '__mro__'):
            return object.__getattribute__(self, item)
        if item in ('__path__', '__file__', '__spec__'):
            raise AttributeError(item)
        if item == '__name__':
            return self._name
        if item == '__class__':
            return type(self._name, (object,), {})

        full_path = f"{self._name}.{item}"
        sig_key = _get_logical_signature(full_path)

        # Look for explicit attribute mock (e.g., constants)
        found, mock_val = _track_and_get_mock(sig_key, None, None)
        if found:
            return mock_val

        if "Error" in item or "Exception" in item:
            class MockException(Exception): pass
            MockException.__name__ = item
            return MockException

        if item.startswith('__') and item.endswith('__'):
            raise AttributeError(item)

        # Return proxy to allow chaining (e.g., module.submodule.func())
        # The halt will happen in __call__ if the user actually invokes it.
        return LLMMockProxy(full_path)

    def __setattr__(self, name, value):
        if name in ('_name', '__bases__', '__mro__'):
            object.__setattr__(self, name, value)
        pass

    def __call__(self, *args, **kwargs):
        sig_key = _get_logical_signature(self._name, args, kwargs)
        found, mock_val = _track_and_get_mock(sig_key, args, kwargs)

        # 1. API found in mock_state: return the recorded value (even if it's None)
        if found:
            print(f"✅ [Mock Hit] API '{self._name}' found in mock_state, returning: {repr(mock_val)[:100]}")
            return mock_val

        # 2. API NOT found in mock_state: need to prompt LLM
        print(f"⚠️ [Mock Miss] API '{self._name}' not found in mock_state, consulting LLM...")

        def _safe_repr(val, max_len=150):
            try:
                r = repr(val)
                if len(r) > max_len:
                    return r[:max_len//2] + "..." + r[-max_len//2:]
                return r
            except Exception:
                return "<Unrepresentable Object>"

        call_details = {
            "api_path": str(self._name),
            "signature": str(sig_key),
            "args": [_safe_repr(a) for a in args],
            "kwargs": {str(k): _safe_repr(v) for k, v in kwargs.items()}
        }

        # FAIL FAST: API lacks mock data. Halt execution immediately!
        print(f"\n" + "🔥"*25)
        print(f"🚨 [Origin Intercept] API '{self._name}' called but lacks mock data.")
        print(f"📦 Arguments intercepted: args={call_details['args']}, kwargs={call_details['kwargs']}")
        print(f"🛑 Halting execution and consulting LLM Agent...")
        print("🔥"*25 + "\n")

        # Capture the current stack trace omitting this immediate function call
        tb_list = traceback.format_stack()[:-1]
        tb_str = "".join(tb_list)

        error_msg = (
            f"MockMissingError: Execution halted at '{sig_key}'. The mock engine requires a return value for this API call to proceed.\n\n"
            f"Full Arguments intercepted:\n{json.dumps(call_details, indent=2)}\n\n"
            f"⚠️ TASK: You MUST generate a JSON patch to mock this API.\n"
            f"For the API ('{sig_key}'), provide ONLY:\n"
            f"1. 'description' (what the API does)\n"
            f"2. 'return_value' (the mocked output required to bypass this failure and satisfy the business logic).\n\n"
            f"Expected JSON Format:\n"
            f"{{\n"
            f"  \"description\": \"...\",\n"
            f"  \"return_value\": ...\n"
            f"}}\n\n"
            f"Stack Trace:\n{tb_str}"
        )

        try:
            import llm_client
            patch = llm_client.API_feature(error_msg, _recent_mock_calls)
            if patch and "return_value" in patch:
                # Extract API name without parentheses and parameters
                api_name = self._name
                # Always record parameters, even if empty (to distinguish no-param calls from other calls)
                # The new format will be handled by _update_state_and_save to append to parameters list
                wrapped_patch = {
                    "api_features": {
                        api_name: {
                            "description": patch.get("description", "Auto-generated mock by LLM"),
                            "parameters": {
                                "args": call_details["args"] if call_details["args"] else [],
                                "kwargs": call_details["kwargs"] if call_details["kwargs"] else {}
                            },
                            "return_value": patch["return_value"]
                        }
                    }
                }
                _update_state_and_save(wrapped_patch)

                # Check if this is adding a new parameter configuration to an existing API
                root_pkg = api_name.split('.')[0].split('(')[0]
                existing_api = mock_state.get("mocked_imports", {}).get(root_pkg, {}).get("api_features", {}).get(api_name)
                if existing_api and "parameters" in existing_api and isinstance(existing_api["parameters"], list):
                    param_count = len(existing_api["parameters"])
                    print(f"✅ [LLM Mock] New parameter configuration added! API '{api_name}' now has {param_count} parameter configurations.")
                else:
                    print(f"✅ [LLM Mock] First parameter configuration created for API '{api_name}'.")

                print("🛑 [LLM Mock] Patch applied! Forcefully terminating process. Please restart.")
            else:
                print("❌ [Fix Failed] Agent failed to generate a valid remediation patch (missing 'return_value').")
        except Exception as ex:
            print(f"⚠️ [System Error]: {ex}")

        # Suicide to allow external script/harness to restart with new state
        import os
        os._exit(1)

    def __iter__(self):
        yield LLMMockProxy(f"{self._name}_item")

    def __getitem__(self, key):
        sig_key = f"{self._name}[{repr(key)}]"
        found, mock_val = _track_and_get_mock(sig_key, None, None)
        if found:
            return mock_val
        # If subscript access lacks data, we can also halt here if needed
        return LLMMockProxy(sig_key)

    def __len__(self): return 1
    def __bool__(self): return True
    def __str__(self): return ""
    def __repr__(self): return self._name

class GhostModule(types.ModuleType):
    def __getattr__(self, name):
        full_path = f"{self.__name__}.{name}"
        sig_key = _get_logical_signature(full_path)

        found, mock_val = _track_and_get_mock(sig_key, None, None)
        if found:
            return mock_val

        if "Error" in name or "Exception" in name:
            class MockException(Exception): pass
            MockException.__name__ = name
            return MockException

        if name.startswith('__') and name.endswith('__'):
            raise AttributeError(name)

        return LLMMockProxy(full_path)

class GhostLoader:
    def __init__(self, fullname): self.fullname = fullname
    def create_module(self, spec):
        import sys as _sys; _sys.stderr.write(f"[DEBUG] create_module called for {self.fullname}\n"); _sys.stderr.flush()
        mod = GhostModule(self.fullname)
        mod.__path__ = []
        return mod
    def exec_module(self, module):
        import sys as _sys; _sys.stderr.write(f"[DEBUG] exec_module called for {module.__name__}\n"); _sys.stderr.flush()
        module.__dict__.update({'__path__': []})


class GhostFinder:
    def find_spec(self, fullname, path, target=None):
        # 1. Filter out built-in and private modules
        if fullname.startswith('_') or fullname in sys.builtin_module_names:
            return None

        base_name = fullname.split('.')[0]

        if hasattr(sys, 'stdlib_module_names') and base_name in sys.stdlib_module_names:
            return None

        # 2. Filter out blacklisted modules (e.g., underlying framework modules)
        if base_name in IGNORED_MODULES:
            return None

        # ==================== Mock Mode Logic ====================
        # Reaching this point means the standard PathFinder has already failed.
        # Therefore, the package is definitely NOT installed in the environment.

        # 3. Check if the package is in the requirements whitelist (ALLOWED_MOCKS)
        if ALLOWED_MOCKS:
            # First check direct match
            if base_name in ALLOWED_MOCKS:
                print(f"[⚙️ Ghost Engine] Auto-pretending successful import of uninstalled package: '{fullname}'")
                _record_mocked_import(fullname)
                return ModuleSpec(fullname, GhostLoader(fullname))

            # If not found, try to resolve using the mapping file
            # Check if any package in REQUIRED_PACKAGES resolves to this import name
            for req_pkg in REQUIRED_PACKAGES:
                resolved_import = _resolve_import_name(req_pkg)
                if resolved_import == base_name:
                    print(f"[⚙️ Ghost Engine] Resolved '{fullname}' as import name for PyPI package '{req_pkg}'")
                    print(f"[⚙️ Ghost Engine] Auto-pretending successful import of uninstalled package: '{fullname}'")
                    _record_mocked_import(fullname)
                    return ModuleSpec(fullname, GhostLoader(fullname))

            # Not in the whitelist and no mapping found: do not intercept.
            # Return None to let the system naturally raise a ModuleNotFoundError.
            return None

# Insert GhostFinder to intercept imports
ghost_finder = GhostFinder()
sys.meta_path.append(ghost_finder)

