activate_audio_infos: true
activate_internet_search: false
activate_skills_lib: false
active_personality_id: -1
allowed_origins:
- 127.0.1.1
audio_auto_send_input: true
audio_in_language: en-US
audio_out_voice: null
audio_pitch: 1
audio_silenceTimer: 5000
auto_read: false
auto_save: true
auto_show_browser: true
auto_speak: false
auto_sync_bindings: true
auto_sync_extensions: true
auto_sync_models: true
auto_sync_personalities: true
auto_title: false
auto_update: true
binding_name: null
copy_to_clipboard_add_all_details: false
ctx_size: 4084
current_language: en
current_voice: null
data_vectorization_activate: true
data_vectorization_build_keys_words: false
data_vectorization_chunk_size: 512
data_vectorization_force_first_chunk: false
data_vectorization_make_persistance: false
data_vectorization_method: tfidf_vectorizer
data_vectorization_nb_chunks: 2
data_vectorization_overlap_size: 128
data_vectorization_save_db: false
data_vectorization_visualize_on_vectorization: false
data_visualization_method: PCA
debug: false
debug_log_file_path: ''
discussion_db_name: default
discussion_prompt_separator: '!@>'
elastic_search_service: false
elastic_search_url: http://localhost:9200
enable_lollms_service: false
enable_motion_ctrl_service: false
enable_ollama_service: false
enable_petals_service: false
enable_sd_service: false
enable_vllm_service: false
enable_voice_service: false
extensions: []
force_accept_remote_access: false
force_output_language_to_be: null
fun_mode: false
hardware_mode: nvidia-tensorcores
headless_server_mode: false
host: 0.0.0.0
internet_activate_search_decision: false
internet_nb_search_pages: 3
internet_quick_search: false
internet_vectorization_chunk_size: 512
internet_vectorization_nb_chunks: 2
internet_vectorization_overlap_size: 128
lollms_base_url: http://localhost:1234
max_summary_size: 512
media_on: false
min_n_predict: 512
model_name: null
model_type: null
model_variant: null
motion_ctrl_base_url: http://localhost:7861
n_predict: 1024
n_threads: 8
negative_boost: null
ollama_base_url: http://localhost:11434
override_personality_model_parameters: false
pdf_latex_path: null
personalities: []
petals_base_url: http://localhost:8064
petals_device: cuda
petals_model_path: TinyLlama/TinyLlama-1.1B-Chat-v1.0
port: 9090
positive_boost: null
repeat_last_n: 40
repeat_penalty: 1.2
sd_base_url: http://localhost:7860
seed: -1
show_code_of_conduct: true
show_news_panel: true
skills_lib_database_name: default
summerize_discussion: false
temperature: 0.9
top_k: 50
top_p: 0.95
turn_on_code_execution: true
turn_on_code_validation: true
turn_on_open_file_validation: false
turn_on_send_file_validation: false
use_files: true
use_user_informations_in_discussion: false
use_user_name_in_discussions: false
user_avatar: default_user.svg
user_description: ''
user_name: user
version: 74
vllm_gpu_memory_utilization: 0.9
vllm_max_model_len: 4096
vllm_max_num_seqs: 256
vllm_model_path: TinyLlama/TinyLlama-1.1B-Chat-v1.0
vllm_url: http://localhost:8000
whisper_model: base
xtts_base_url: http://localhost:8020
